config/routes.rb
AssetManager::Application.routes.draw do

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/about',   to: 'static_pages#about'
  match '/help',    to: 'static_pages#help'
  match '/search',  to: 'assets#search'
  match '/last_month', to: 'assets#last_30_days'

  resources :users do
    collection { post :import }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :assets do
   collection { post :import }
  end
  resources :password_resets
end

app/models/asset.rb
# == Schema Information
#
# Table name: assets
#
#  id                :integer         not null, primary key
#  asset_description :string(255)
#  asset_type        :string(255)
#  status            :string(255)
#  serial_no         :string(255)
#  user_id           :integer
#  cost              :decimal(, )
#  barcode           :string(255)
#  comment           :string(255)
#  date_purchased    :date
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#
class Asset < ActiveRecord::Base
  attr_accessible :asset_description, :asset_type, :comment, :date_purchased, :serial_no, :status, :user_id, :cost, :barcode, :image, :original_updated_at
  belongs_to :user
  delegate :name, to: :user, prefix: true
  validates  :user_id, presence: true
  validates  :asset_description, presence: true
  validates  :asset_type, presence: true
  validates  :serial_no, presence: true, uniqueness: true
  validates  :status, presence: true
  validates  :comment, length: { maximum: 150 }
  validate   :handle_conflict, only: :update

  mount_uploader :image, ImageUploader

  include PgSearch
  pg_search_scope :search, against: [:asset_description, :status, :asset_type, :comment, :serial_no],
      using: {tsearch: { dictionary: "english", prefix: true }},
      associated_against: { user: :name }

  #older assets first
  default_scope order: 'assets.created_at ASC'

  def self.text_search(query)
    if query.present?
      search(query)
    else
      scoped
    end
  end

  #for optimistic locking
  def original_updated_at
    @original_updated_at || updated_at.to_f
  end
  attr_writer :original_updated_at

  #optimistic locking heavy lifting
  def handle_conflict
    if @conflict || updated_at.to_f > original_updated_at.to_f
      @conflict = true
      @original_updated_at = nil
      errors.add :base, "This record changed while you were editing. Take these change into account and submit it again"
      changes.each do |attribute, values|
        errors.add attribute, "was #{values.first}"
      end
    end
  end

  #import assets from the old system
  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      asset.user = find_by_id(spreadsheet.cell(i, 'E'))
      asset = find_or_initialize_by_id(spreadsheet.cell(i, 'A')) || new
      asset.attributes = row.to_hash.slice(*accessible_attributes)
      asset.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv'
      then Csv.new(file.path, nil, :ignore)
    when '.xls'
      then Roo::Excel.new(file.path, nil, :ignore)
    when '.xlsx'
      then Roo::Excelx.new(file.path, nil, :ignore)
    else
      raise "Uknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :signed_in_user
  before_filter :admin_user, only: [:edit, :update, :import]

  def create
    @asset = current_user.assets.build(params[:asset])
    if @asset.save
      redirect_to root_path
      flash.now[:success] = "Asset created!"
    else
      render 'static_pages/home'
    end
  end

  def show
    @asset = Asset.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = AssetPdf.new(@asset)
        send_data pdf.render, filename:    "asset_#{@asset.id}.pdf",
                              type:        "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def update
    @asset = Asset.find(params[:id])
    if @asset.update_attributes(params[:asset])
      redirect_to @asset, notice: "Profile updated"
    else
      render 'edit'
    end
  end

  def search
    @assets = Asset.text_search(params[:query]).page(params[:page]).per_page(10)
  end

  def index
    @assets = Asset.includes(:user).paginate(page: params[:page])
  end

  def import
    Asset.import(params[:file])
    redirect_to assets_path, notice: "Assets imported"
  end

  def last_30_days
    @assets = Asset.where("updated_at >= ?", 30.days.ago).page(params[:page]).per_page(10)
  end

  private
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/assets_helper.rb
module AssetsHelper

  def options_for_status(defaults)
    options_for_select([["Allocated"], ["Stock"], ["Written Off"]], @asset.status)
  end
end

app/views/assets/_asset.html.haml
%li
  %span.id= link_to "#{ENV['asset_pre']}#{asset.id}", asset
  .edit
    - if current_user.admin?
      = link_to "edit", edit_asset_path(asset), class: "btn btn-small"
  %span.serial
    = asset.serial_no
    %br/
  %span.status
    Status: #{asset.status}
  %span.type
    Type: #{asset.asset_type}
    %br/
  %span.description
    Description: #{asset.asset_description}
    %br/
  %span.comment
    %em= asset.comment
  %span.misc
    %br>/
    Added #{time_ago_in_words(asset.created_at)} ago.
    %br/
    Assigned to: #{link_to asset.user_name, asset.user}
    = succeed "Date" do
      %br/
    Purchased: #{asset.date_purchased}
    - if current_user.admin?
      %br>/
      Cost: #{number_to_currency(asset.cost, :unit => '£')}
  %br/
  %span
    - if current_user.admin?
      = link_to "Printable PDF", asset_path(asset, format: "pdf")

app/views/assets/edit.html.haml
/
  \# == Schema Information
  \#
  \# Table name: assets
  \#
  \#  id                :integer         not null, primary key
  \#  asset_description :string(255)
  \#  asset_type        :string(255)
  \#  status            :string(255)
  \#  serial_no         :string(255)
  \#  user_id           :integer
  \#  cost              :decimal(, )
  \#  barcode           :string(255)
  \#  comment           :string(255)
  \#  date_purchased    :date
  \#  created_at        :datetime        not null
  \#  updated_at        :datetime        not null
  \#
- provide(:title, "Edit Asset")
%h1 Update the asset
.row
  .span5.offset3
    = form_for(@asset) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :asset_description, "Description"
      = f.text_field :asset_description
      = f.label :asset_type, "Asset Type"
      = f.text_field :asset_type
      = f.label :status, "Status"
      = f.select :status, options_for_status(params[:defaults])
      = f.label :serial_no, "Serial No"
      = f.text_field :serial_no
      = f.label :cost, "Cost"
      = f.text_field :cost
      = f.label :barcode, "Barcode:"
      = f.text_field :barcode
      = f.label :comment, "Comments?"
      = f.text_field :comment
      = f.label :date_purchased, "Date Purchased:"
      = f.date_select :date_purchased, order: [:day, :month, :year]
      = f.label :user_id, "Allocated to"
      = collection_select(:asset, :user_id, User.all, :id, :name, prompt: true)
      = f.label :image, "Image"
      = f.file_field :image
      = f.hidden_field :original_updated_at
      = f.submit "Save changes", class: "btn btn-large btn-primary"

app/views/assets/index.html.haml
= provide(:title, 'Assets')
%h1 All assets
- if current_user.admin?
  %h2 Import assets
  = form_tag import_assets_path, multipart: true do
    = file_field_tag :file
    = submit_tag "Import", class: 'btn btn-small'
= will_paginate @assets
%ol.assets
  = render @assets
= will_paginate @assets

app/views/assets/last_30_days.html.haml
- provide(:title, 'Last Month')
%h1 Updated in the last month
= will_paginate @assets
%ol.assets
  = render @assets
= will_paginate @assets

app/views/assets/search.html.haml
= provide(:title, 'Search')
%h1 Search
= form_tag search_path, method: :get do
  .row
    %span.span4
      = text_field_tag :query, params[:query]
    = submit_tag "Search", name: nil, class: "btn btn-small", id: "srch_btn"
#assets
  = will_paginate @assets
  %ol.assets
    = render @assets
  = will_paginate @assets

app/views/assets/show.html.haml
- provide(:title, "Asset #{@asset.id}")
%ul.breadcrumb
  %li
    = link_to 'Home', root_path
    %span.divider /
  %li
    = link_to 'Assets', assets_path
    %span.divider /
  %li.active= "#{ENV['asset_pre']}#{@asset.id}"
.row
  %aside.span7
    %section
      %h1= "#{ENV['asset_pre']}#{@asset.id}"
  .span12
    %ol.assets
      = render @asset
    - if @asset.image?
      = image_tag @asset.image_url(:thumb).to_s
      %br/
      = link_to "Full Image", @asset.image_url.to_s