config/routes.rb
AssetManager::Application.routes.draw do

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/about',   to: 'static_pages#about'
  match '/help',    to: 'static_pages#help'
  match '/search',  to: 'assets#search'
  match '/last_month', to: 'assets#last_30_days'

  resources :users do
    collection { post :import }
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :assets do
   collection { post :import }
  end
  resources :password_resets
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    = link_to 'Asset Manager by Ryan MacGillivray', 'http://github.com/RyanMacG'
  %nav
    %ul
      %li= link_to ENV['comp_address_text'], ENV['comp_address']
      %li= link_to "About", about_path
      %li= link_to "Help", help_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to ENV['comp_logo'], root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          - if signed_in?
            / should change the links at the top if the user is signed in
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Assets
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Add an Asset", root_path
                %li= link_to "Asset List",   assets_path
                %li= link_to "Asset Search", search_path
            - if current_user.admin?
              %li#fat-menu.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Reports
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Last Month", last_month_path
            %li= link_to "Users", users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Me", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application-all", :media => "all"
    = stylesheet_link_tag "print", :media => "print"
    /[if IE]
      <haml:loud> stylesheet_link_tag &amp;quot;application-ie&amp;quot;, :media =&amp;gt; &amp;quot;all&amp;quot; </haml:loud>
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?
    = javascript_include_tag "application"